exports.keydb={
    mysql:{
        host:'bouzilbgn7yedujlmj4t-mysql.services.clever-cloud.com',
        username:'uqkzyvu6tl33pbxr',
        password:'Dvwa7YIIJVaJet0nKykv',
        database:'bouzilbgn7yedujlmj4t',
        port:3306,
        dialect:'mysql'    
    }
}